# Generated by Django 4.2.5 on 2023-11-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(default='https://picsum.photos/200', upload_to='uploads/products/'),
        ),
    ]
