# Generated by Django 4.2.5 on 2023-11-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_customer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(default='uploads/products/download.jfif', upload_to='uploads/products/'),
        ),
    ]
